// import { useEffect, useState } from 'react';
// import { useRouter } from 'next/router';
// import { getCartData, removeFromCart } from '../util/cart';

// export default function CartPage() {
//   const [cart, setCart] = useState([]);
//   const router = useRouter();

//   useEffect(() => {
//     // Fetch cart data when component mounts
//     const cartData = getCartData();
//     setCart(cartData);
//   }, []);

//   const handleRemoveItem = (productId) => {
//     // Remove item from cart
//     removeFromCart(productId);
//     // Refresh cart data
//     const updatedCart = getCartData();
//     setCart(updatedCart);
//   };

//   const handleCheckout = () => {
//     // Navigate to the checkout page
//     router.push('/checkout');
//   };

//   return (
//     <div>
//       <h1>Your Cart</h1>
//       {cart.length === 0 ? (
//         <p>Your cart is empty</p>
//       ) : (
//         <div>
//           {cart.map((item) => (
//             <div key={item.productId}>
//               <p>{item.name}</p>
//               <p>Quantity: {item.quantity}</p>
//               <p>Subtotal: {item.price * item.quantity}</p>
//               <button onClick={() => handleRemoveItem(item.productId)}>Remove</button>
//             </div>
//           ))}
//           <p>Total: {cart.reduce((acc, item) => acc + item.price * item.quantity, 0)}</p>
//           <button onClick={handleCheckout}>Checkout</button>
//         </div>
//       )}
//     </div>
//   );
// }

export const metadata = {
  default: 'Cart Page',
  description: 'Generated by create next app',
};

export default function CartPage() {
  return (
    <div>
      <h1>Cart Page</h1>
    </div>
  );
}
