export const metadata = {
  default: 'Cart Page',
  description: 'Generated by create next app',
};

export default function CartPage() {
  return (
    <div>
      <h1>Cart Page</h1>
    </div>
  );
}
