export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return (
    <div>
      <h1>About us</h1>
      <div>This is a Store for selling ...</div>
    </div>
  );
}
