export const metadata = {
  title: {
    default: 'About | Store',
    template: '%s | Store',
  },
  description: 'Generated by create next app',
};

export default function AboutPage() {
  return <div>About page</div>;
}
