import Image from 'next/image';
import Link from 'next/link';
import { getProductsInsecure } from '../../database/products';

export const metadata = {
  title: 'Products page',
  description: 'Generated by create next app',
};

// export default async function ProductsPage() {
//   try {
//     const products = await getProductsInsecure();

//     if (!Array.isArray(products)) {
//       console.error('Products is not an array:', products);
//       return <div>No products available.</div>;
//     }

//     return (
//       <div>
//         <h1>Products you can buy:</h1>
//         {products.map((product) => (
//           <div key={`products-${product.id}`}>
//             <a data-test-id="product-1">{product.name}</a>
//             <Link href={`/products/${product.id}`}>
//               <div>{product.name}</div>
//               <Image
//                 src={`/images/${product.name.toLowerCase()}.webp`}
//                 width={300}
//                 height={200}
//                 alt={product.name}
//               />
//             </Link>
//           </div>
//         ))}
//       </div>
//     );
//   } catch (error) {
//     console.log('Error in ProductsPage:', error);
//     return <div>Error loading products.</div>;
//   }
// }

export default async function ProductsPage() {
  const products = await getProductsInsecure();

  return (
    <div>
      <h1>Products you can buy:</h1>
      {products.map((product) => {
        return (
          <div
            key={`products-${product.id}`}
            data-test-id={`product-type-${product.type}`}
          >
            <Link href={`/products/${product.id}`}>
              <div>{product.name}</div>
              <Image
                src={`/images/${product.name.toLowerCase()}.webp`}
                width={200}
                height={200}
                alt={product.name}
              />
            </Link>
          </div>
        );
      })}
    </div>
  );
}
