import Image from 'next/image';
import Link from 'next/link';
import { getProductsInsecure } from '../../database/products';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default async function ProductsPage() {
  const products = await getProductsInsecure();

  return (
    <div>
      <h1>The Products:</h1>
      {products.map((product) => {
        return (
          <div key={`products-${product.id}`}>
            <a data-test-id="product-1">{product.name}</a>
            <Link href={`/products/${product.id}`}>
              <div>{product.name}</div>
              <Image
                src={`/images/${product.name.toLowerCase()}.webp`}
                width={300}
                height={200}
                alt={product.name}
              />
            </Link>
          </div>
        );
      })}
    </div>
  );
}
