import Image from 'next/image';
import Link from 'next/link';
import { getProducts } from '../../database/products';

export const metadata = {
  title: 'Products | Store',
  description: 'Generated by create next app',
};

export default function ProductsPage() {
  const products = getProducts();

  return (
    <div>
      This are my Products
      {products.map((product) => {
        return (
          <div key={`products-${product.id}`}>
            <Link href={`/products/${product.id}`}>
              <div>{product.name}</div>
              <Image
                src={`/images/${product.name.toLowerCase()}.jpg`}
                width={300}
                height={200}
                alt={product.name}
              />
            </Link>
          </div>
        );
      })}
    </div>
  );
}
